AWSTemplateFormatVersion: 2010-09-09
Description: "AWS cloudformation template for EC2 Instance"

Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-040c7ad0a93be494e
      InstanceType: t2.micro
      KeyName: mottu
      SecurityGroups:
        - default        
        - !Ref SSHSecurityGroup 
      AvailabilityZone: ap-south-1  
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: My new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

